interface Hotel {
  id: number;
  description: string;
  name: string;
  reviewCount: number;
  rating: number;
  image: string;
  tag: string[];
  location: string;
  distance: string;
  sustainability: string;
  propertyFeatures: string;
  roomType: string;
  originalPrice: string;
  currentPrice: string;
  taxesAndCharges: string;
  prepayment: string;
}
  
export const hotelInfo: Hotel[] = [
 
  {
    id: 6982744,
    description: "Nascent Gardenia Residence.\n4 out of 5 stars.\n8.3 Very good 210 reviews.\n6 km from centre.\nTravel Sustainable.\nHotel room: 1 bed.",
    name: "Nascent Gardenia Residence",
    reviewCount: 210,
    rating: 8.3,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/344536573.jpg?k=b3548c9a16aac96d858559d57d9238203165bc4e34d30238482dd02020a17ab5&o=",
    tag: ["All", "Free cancellation", "No prepayment needed", "Dhaka"],
    location: "Dhaka",
    distance: "6 km from centre",
    sustainability: "Travel Sustainable",
    propertyFeatures: "1 bed",
    roomType: "Hotel room",
    originalPrice: "83 USD",
    currentPrice: "62 USD",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: "Free cancellation, No prepayment needed"
  },
  {
    id: 9130663,
    description: "Hotel Shuktara Dhaka.\n3 out of 5 stars.\n8.1 Very good 746 reviews.\n4.4 km from centre.\nTravel Sustainable.\nHotel room: 2 beds.",
    name: "Hotel Shuktara Dhaka",
    reviewCount: 746,
    rating: 8.1,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/442584100.jpg?k=7ef0b4e5d26d8c8dd792ad4a13c6530571893af55f2df194d1a6903e4a1009c2&o=",
    tag: ["All", "Free cancellation", "No prepayment needed", "Dhaka"],
    location: "Dhaka",
    distance: "4.4 km from centre",
    sustainability: "Travel Sustainable",
    propertyFeatures: "2 beds",
    roomType: "Hotel room",
    originalPrice: "92 USD",
    currentPrice: "43 USD",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: "Free cancellation, No prepayment needed"
  },
  {
    id: 582848,
    description: "Hotel 71.\n3 out of 5 stars.\n7.8 Good 1399 reviews.\n1.3 km from centre.\nTravel Sustainable.\n1 bed.",
    name: "Hotel 71",
    reviewCount: 1399,
    rating: 7.8,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/21860203.jpg?k=b2e8540a576607d2d1df65132ce98f0be6ebae7393343432427caca6675b10f1&o=",
    tag: ["All", "Free cancellation", "No prepayment needed", "Dhaka"],
    location: "Dhaka",
    distance: "1.3 km from centre",
    sustainability: "Travel Sustainable",
    propertyFeatures: "1 bed",
    roomType: "Hotel room",
    originalPrice: "76 USD",
    currentPrice: "43 USD",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: "Free cancellation, No prepayment needed"
  },
  {
    id: 9670810,
    description: "Hotel Grand Circle Inn Dhaka.\n3 out of 5 stars.\n8.3 Very good 118 reviews.\n2.2 km from centre.\nTravel Sustainable.\nHotel room: 2 beds.",
    name: "Hotel Grand Circle Inn Dhaka",
    reviewCount: 118,
    rating: 8.3,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/519252321.jpg?k=c52bdde7ce3467e2d03e9a3169bfee56b4f860297529c324ce73ccdaa797bd19&o=",
    tag: ["All", "Free cancellation", "No prepayment needed", "Dhaka"],
    location: "Dhaka",
    distance: "2.2 km from centre",
    sustainability: "Travel Sustainable",
    propertyFeatures: "2 beds",
    roomType: "Hotel room",
    originalPrice: "44 USD",
    currentPrice: "33 USD",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: "Free cancellation, No prepayment needed"
  },
  {
    id: 1794582,
    description: "Asia Hotel & Resorts.\n3 out of 5 stars.\n7.5 Good 132 reviews.\n800 m from centre.\nHotel room: 1 bed.",
    name: "Asia Hotel & Resorts",
    reviewCount: 132,
    rating: 7.5,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/82616916.jpg?k=f2979302b1e001f93d12a508fa5ba40283cc8951d6167843106b698979634f34&o=",
    tag: ["All", "Free cancellation", "No prepayment needed", "Dhaka"],
    location: "Dhaka",
    distance: "800 m from centre",
    sustainability: "Travel Sustainable",
    propertyFeatures: "1 bed",
    roomType: "Hotel room",
    originalPrice: "46 USD",
    currentPrice: "45.54 USD",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: "Free cancellation, No prepayment needed"
  },
  {
    id: 8965751,
    description: "Priyo Nibash Stylish Residential Hotel.\n4 out of 5 stars.\n7.9 Good 329 reviews.\n3.9 km from centre.\nTravel Sustainable.\nHotel room: 1 bed.",
    name: "Priyo Nibash Stylish Residential Hotel",
    reviewCount: 329,
    rating: 7.9,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/499371398.jpg?k=0bbe2c063066c5ee837d1315a0a66a1bb98ad6dea223711892614c45cb5e5800&o=",
    tag: ["All", "Mobile-only price", "Free cancellation", "No prepayment needed", "Dhaka"],
    location: "Dhaka",
    distance: "3.9 km from centre",
    sustainability: "Travel Sustainable",
    propertyFeatures: "1 bed",
    roomType: "Hotel room",
    originalPrice: "40 USD",
    currentPrice: "36 USD",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: "Free cancellation, No prepayment needed"
  },
  {
    id: 9299899,
    description: "Hotel Afford Inn.\n3 out of 5 stars.\n7.2 Good 479 reviews.\nUttara • 15 km from centre.\nTravel Sustainable.\nHotel room: 1 bed.",
    name: "Hotel Afford Inn",
    reviewCount: 479,
    rating: 7.2,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/412188205.jpg?k=b94ba73d4e2b3763456877a38fadf66f390abeffe2c0f8273f21e8a9b1c32258&o=",
    tag: ["All", "Free cancellation", "No prepayment needed", "Dhaka"],
    location: "Uttara, Dhaka",
    distance: "15 km from centre",
    sustainability: "Travel Sustainable",
    propertyFeatures: "1 bed",
    roomType: "Hotel room",
    originalPrice: "34 USD",
    currentPrice: "31 USD",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: "Free cancellation, No prepayment needed"
  },

  {
    id: 621628,
    description: "Hotel Victory - Best in City Center.\n3 out of 5 stars.\n7.6 Good 64 reviews.\n‎1.5 km from centre‬.\nHotel room: 1 bed.\nOriginal price 56 USD. Current price 32 USD.\nIncludes taxes and charges.\nFree cancellation.\nNo prepayment needed.",
    name: "Hotel Victory - Best in City Center",
    reviewCount: 64,
    rating: 7.6,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/352353717.jpg?k=50083c071b919179f0ddbaeb4938dc9f424cbd1e8664328dd875dda049f02315&o=",
    tag: ["All", "Mobile-only price", "Free cancellation", "No prepayment needed", "Dhaka"],
    location: "Dhaka",
    distance: "1.5 km from centre",
    sustainability: "",
    propertyFeatures: "1 bed",
    roomType: "Hotel room",
    originalPrice: "56 USD",
    currentPrice: "32 USD",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: "Free cancellation, No prepayment needed"
  },
  {
    id: 469851,
    description: "INNOTEL BATON ROUGE - A Luxury Collection Hotel.\n4 out of 5 stars.\n7.1 Good 378 reviews.\n‎Gulshan‬ • ‎8 km from centre‬\n‎Travel Sustainable‬.\nHotel room: 1 bed.\nOriginal price 70 USD. Current price 38 USD.\nIncludes taxes and charges.\nFree cancellation.\nNo prepayment needed.",
    name: "INNOTEL BATON ROUGE - A Luxury Collection Hotel",
    reviewCount: 378,
    rating: 7.1,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/393430549.jpg?k=d486d2358340027aebce29482689db826cccc8621622f12f4b07fa07df57fb1a&o=",
    tag: ["All", "Mobile-only price", "Free cancellation", "No prepayment needed", "Dhaka"],
    location: "Gulshan, Dhaka",
    distance: "8 km from centre",
    sustainability: "Travel Sustainable",
    propertyFeatures: "1 bed",
    roomType: "Hotel room",
    originalPrice: "70 USD",
    currentPrice: "38 USD",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: "Free cancellation, No prepayment needed"
  },
  {
    id: 621624,
    description: "FARS Hotel & Resorts - BAR-Buffet-Pool-SPA.\n4 out of 5 stars.\n7.2 Good 195 reviews.\n‎950 m from centre‬\n‎Travel Sustainable‬.\nHotel room: 2 beds.\nOriginal price 158 USD. Current price 90 USD.\nIncludes taxes and charges.\nFree cancellation.\nNo prepayment needed.",
    name: "FARS Hotel & Resorts - BAR-Buffet-Pool-SPA",
    reviewCount: 195,
    rating: 7.2,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/513143243.jpg?k=52cfe8eaa60b8d3833a59c91f9c75b2ff4ecd7123249aa1bd1fbab527454e6fc&o=",
    tag: ["All", "Mobile-only price", "Free cancellation", "No prepayment needed", "Dhaka"],
    location: "Dhaka",
    distance: "950 m from centre",
    sustainability: "Travel Sustainable",
    propertyFeatures: "2 beds",
    roomType: "Hotel room",
    originalPrice: "158 USD",
    currentPrice: "90 USD",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: "Free cancellation, No prepayment needed"
  },
  {
    id: 11309706,
    description: "Hotel Rose Garden Palace Residential.\n2 out of 5 stars.\n7.4 Good 20 reviews.\n‎4.2 km from centre‬.\nHotel room: 1 bed.\nOriginal price 24 USD. Current price 21 USD.\nIncludes taxes and charges.\nFree cancellation.\nNo prepayment needed.",
    name: "Hotel Rose Garden Palace Residential",
    reviewCount: 20,
    rating: 7.4,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/518775067.jpg?k=3929db1a6b9b94462bf03e18ba3f43c7ac07b586c7eac6ae7b2cd94d2e2d3c2a&o=",
    tag: ["All", "Early 2024 Deal", "Free cancellation", "No prepayment needed", "Dhaka"],
    location: "Dhaka",
    distance: "4.2 km from centre",
    sustainability: "",
    propertyFeatures: "1 bed",
    roomType: "Hotel room",
    originalPrice: "24 USD",
    currentPrice: "21 USD",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: "Free cancellation, No prepayment needed"
  },
  {
    id: 6664048,
    description: "Hotel Zakaria International.\n2 out of 5 stars.\n7.0 Good 281 reviews.\n‎6 km from centre‬.\nHotel room: 1 bed.\nOriginal price 145 USD. Current price 35 USD.\nIncludes taxes and charges.\nFree cancellation.\nNo prepayment needed.",
    name: "Hotel Zakaria International",
    reviewCount: 281,
    rating: 7.0,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/283972965.jpg?k=a37a04d68c09806c51b9032d361b82902643666c49cc0313685b5e58ef66e653&o=",
    tag: ["All", "Mobile-only price", "Free cancellation", "No prepayment needed", "Dhaka"],
    location: "Dhaka",
    distance: "6 km from centre",
    sustainability: "",
    propertyFeatures: "1 bed",
    roomType: "Hotel room",
    originalPrice: "145 USD",
    currentPrice: "35 USD",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: "Free cancellation, No prepayment needed"
  },
  {
    id: 6044188,
    description: "Renaissance Dhaka Gulshan Hotel.\n5 out of 5 stars.\n8.0 Very good 101 reviews.\n‎Gulshan‬ • ‎7 km from centre‬\n‎Travel Sustainable‬.\nHotel room: 1 bed.\n235 USD.\nIncludes taxes and charges.\nNo prepayment needed.",
    name: "Renaissance Dhaka Gulshan Hotel",
    rating: 7.5,
    reviewCount: 101,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/444109100.jpg?k=8d04470817133a691a9cf21574231f8bccef1962810bd22ac93186856fef55c5&o=",
    tag: ["All", "Travel Sustainable", "No prepayment needed", "Dhaka"],
    location: "Gulshan, Dhaka",
    distance: "7 km from centre",
    sustainability: "Travel Sustainable",
    propertyFeatures: "1 bed",
    roomType: "Hotel room",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: "No prepayment needed",
    originalPrice: "19 USD",
    currentPrice: "17 USD",
  },

  {
    id: 4535726,
    description: "White Palace Hotel.\n3 out of 5 stars.\n7.8 Good 150 reviews.\n‎Uttara‬ • ‎18 km from centre‬\n‎Travel Sustainable‬.\nHotel room: 1 bed.\n54 USD.\nIncludes taxes and charges.\nFree cancellation.\nNo prepayment needed.",
    name: "White Palace Hotel",
    rating: 8.3,
    reviewCount: 150,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/184403193.jpg?k=fa86a97a1a7e66a98147ec16f38b92d02be08bbfc2ba7157701a1ca12070839e&o=",
    tag: ["All", "Travel Sustainable", "Free cancellation", "No prepayment needed", "Dhaka"],
    location: "Uttara, Dhaka",
    distance: "18 km from centre",
    sustainability: "Travel Sustainable",
    propertyFeatures: "1 bed",
    roomType: "Hotel room",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: "Free cancellation, No prepayment needed",
    originalPrice: "21 USD",
    currentPrice: "19 USD",
  },
  {
    id: 1757950,
    description: "Rafflesia Serviced Apartments.\n4 out of 5 for property rating.\n8.0 Very good 60 reviews.\n‎Gulshan‬ • ‎7 km from centre‬.\nPrivate suite: 1 bed, 2 bathrooms.\n108 USD.\nIncludes taxes and charges.\nFree cancellation.\nNo prepayment needed.",
    name: "Rafflesia Serviced Apartments",
    rating: 7.4,
    reviewCount: 60,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/168998188.jpg?k=af3d5841ba05a39cf69d85a83f7fdb0d4b59338d08b3873f35fb150a88153c13&o=",
    tag: ["All", "Travel Sustainable", "Free cancellation", "No prepayment needed", "Dhaka"],
    location: "Gulshan, Dhaka",
    distance: "7 km from centre",
    sustainability: "Travel Sustainable",
    propertyFeatures: "1 bed, 2 bathrooms",
    roomType: "Private suite",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: "Free cancellation, No prepayment needed",
originalPrice: "17 USD",
    currentPrice: "16 USD",
  },
  {
    id: 7960061,
    description: "The Shahin Residence.\n2 out of 5 stars.\n8.0 Very good 77 reviews.\n‎6 km from centre‬\n‎Travel Sustainable‬.\nHotel room: 1 bed.\nOriginal price 19 USD. Current price 17 USD.\nIncludes taxes and charges.\nFree cancellation.\nNo prepayment needed.",
    name: "The Shahin Residence",
    rating: 8.2,
    reviewCount: 77,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/399035462.jpg?k=2a9e7e5f7b3edc973f63c35d9c4168e02621017faacd04fb52a8b297b2008e8d&o=",
    tag: ["All", "Travel Sustainable", "Mobile-only price", "Free cancellation", "No prepayment needed", "Dhaka"],
    location: "Dhaka",
    distance: "6 km from centre",
    sustainability: "Travel Sustainable",
    propertyFeatures: "1 bed",
    roomType: "Hotel room",
    originalPrice: "19 USD",
    currentPrice: "17 USD",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: "Free cancellation, No prepayment needed"
  },
  {
    id: 8616561,
    description: "Kompass Homestay - Affordable AC Room With Shared Bathroom in Naya Paltan Free WIFI.\n3 out of 5 for property rating.\n7.1 Good 19 reviews.\n‎1.4 km from centre‬.\nRoom with shared bathroom: 1 bed.\nOriginal price 12 USD. Current price 11 USD.\nIncludes taxes and charges.\nNo prepayment needed.",
    name: "Kompass Homestay - Affordable AC Room With Shared Bathroom",
    rating: 7.3,
    reviewCount: 19,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/448136883.jpg?k=2beb508509cf13724330ade21e54def54725a635ce533b90e30ab7ab81b8c841&o=",
    tag: ["All", "Free cancellation", "No prepayment needed", "Mobile-only price", "Dhaka"],
    location: "Naya Paltan, Dhaka",
    distance: "1.4 km from centre",
    sustainability: "Travel Sustainable",
    propertyFeatures: "1 bed",
    roomType: "Room with shared bathroom",
    originalPrice: "12 USD",
    currentPrice: "11 USD",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: "No prepayment needed"
  },
  {
    id: 659278,
    description: "Hotel Sarina.\n5 out of 5 stars.\n7.5 Good 376 reviews.\n‎Gulshan‬ • ‎8 km from centre‬\n‎Travel Sustainable‬.\nHotel room: 1 bed.\nOriginal price 150 USD. Current price 119 USD.\nIncludes taxes and charges.",
    name: "Hotel Sarina",
    rating: 7.5,
    reviewCount: 376,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/389947091.jpg?k=3d3407e478ed69be839ebc782761ef9070861a669a197733fc516b99d9ebce50&o=",
    tag: ["All", "Travel Sustainable", "Mobile-only price", "Dhaka"],
    location: "Gulshan, Dhaka",
    distance: "8 km from centre",
    sustainability: "Travel Sustainable",
    propertyFeatures: "1 bed",
    roomType: "Hotel room",
    originalPrice: "150 USD",
    currentPrice: "119 USD",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: "Free cancellation, No prepayment needed"
  },

  {
    id: 913366,
    description: "Nascent Gardenia Baridhara.\n4 out of 5 stars.\n8.4 Very good 38 reviews.\n‎9 km from centre‬\n‎Travel Sustainable‬.\nHotel room: 2 beds.\nOriginal price 239 USD. Current price 179 USD.\nIncludes taxes and charges.\nFree cancellation.\nNo prepayment needed.",
    name: "Nascent Gardenia Baridhara",
    rating: 8.4,
    reviewCount: 38,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/136262467.jpg?k=37fd7e2eedef804987a4be5254d2bc58693c9e671552291dc11a6a2bdc66f94c&o=",
    tag: ["All", "Travel Sustainable", "Early 2024 Deal", "Free cancellation", "No prepayment needed", "Dhaka"],
    location: "Baridhara, Dhaka",
    distance: "9 km from centre",
    sustainability: "Travel Sustainable",
    propertyFeatures: "2 beds",
    roomType: "Hotel room",
    originalPrice: "239 USD",
    currentPrice: "179 USD",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: "Free cancellation, No prepayment needed"
  },
  {
    id: 10833831,
    description: "Star Residence.\n3 out of 5 stars.\n6.7 Pleasant 23 reviews.\n‎Uttara‬ • ‎19 km from centre‬.\nHotel room: 1 bed.\nOriginal price 19 USD. Current price 15 USD.\nIncludes taxes and charges.\nFree cancellation.\nNo prepayment needed.",
    name: "Star Residence",
    rating: 7.6,
    reviewCount: 23,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/524410499.jpg?k=5d564e263350a4beb98e477fdf7502c2ec4049ff9c1283f265de19d636a7db15&o=",
    tag: ["All", "Free cancellation", "No prepayment needed", "Mobile-only price", "Dhaka"],
    location: "Uttara, Dhaka",
    distance: "19 km from centre",
    sustainability: "Travel Sustainable",
    propertyFeatures: "1 bed",
    roomType: "Hotel room",
    originalPrice: "19 USD",
    currentPrice: "15 USD",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: "Free cancellation, No prepayment needed"
  },

  {
    id: 254830,
    description: "ModernHaus SoHo.\n5 out of 5 stars.\n8.5 Very good 847 reviews.\n‎SoHo‬ • ‎5 km from centre‬\n‎Travel Sustainable‬.\nHotel room: 1 bed.\nOriginal price 547 USD. Current price 473 USD.\nIncludes taxes and charges.\nNo prepayment needed.",
    name: "ModernHaus SoHo",
    rating: 8.5, // Review Score provided
    reviewCount: 847,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/297840629.jpg?k=d20e005d5404a7bea91cb5fe624842f72b27867139c5d65700ab7f69396026ce&o=",
    tag: ["All", "Travel Sustainable", "No prepayment needed", "New York"],
    location: "SoHo, New York",
    distance: "5 km from centre",
    sustainability: "Travel Sustainable",
    propertyFeatures: "1 bed",
    roomType: "Hotel room",
    originalPrice: "547 USD",
    currentPrice: "473 USD",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: "No prepayment needed"
  },
  {
    id: 2012829,
    description: "Doubletree By Hilton New York Times Square West.\n4 out of 5 stars.\n7.0 Good 15149 reviews.\n‎Hell's Kitchen‬ • ‎1.6 km from centre‬\n‎Travel Sustainable‬.\nHotel room: 1 bed.\nOriginal price 163 USD. Current price 147 USD.\nIncludes taxes and charges.\nFree cancellation.\nNo prepayment needed.",
    name: "Doubletree By Hilton New York Times Square West",
    rating: 7.0, // Review Score provided
    reviewCount: 15149,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/485684506.jpg?k=aa6b48a0a762d1d5265a42a24c9da901d9a85121968fbf151b46441078f3a5be&o=",
    tag: ["All", "Travel Sustainable", "Free cancellation", "No prepayment needed", "New York"],
    location: "Hell's Kitchen, New York",
    distance: "1.6 km from centre",
    sustainability: "Travel Sustainable",
    propertyFeatures: "1 bed",
    roomType: "Hotel room",
    originalPrice: "163 USD",
    currentPrice: "147 USD",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: "No prepayment needed"
  },
  {
    id: 2210104,
    description: "Hilton Garden Inn New York Times Square South.\n3 out of 5 stars.\n8.1 Very good 4177 reviews.\n‎Hell's Kitchen‬ • ‎1.8 km from centre‬\n‎Travel Sustainable‬.\nHotel room: 1 bed.\n163 USD.\nIncludes taxes and charges.\nFree cancellation.\nNo prepayment needed.",
    name: "Hilton Garden Inn New York Times Square South",
    rating: 8.1, // Review Score provided
    reviewCount: 4177,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/485847819.jpg?k=c8a7d6fe3756b65ddf1e88e4ece012a9e377f4da075e7f6c65d0064bee9dab61&o=",
    tag: ["All", "Travel Sustainable", "Free cancellation", "No prepayment needed", "New York"],
    location: "Hell's Kitchen, New York",
    distance: "1.8 km from centre",
    sustainability: "Travel Sustainable",
    propertyFeatures: "1 bed",
    roomType: "Hotel room",
    originalPrice: "163 USD",
    currentPrice: "163 USD",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: "No prepayment needed"
  },
  {
    id: 436827,
    description: "The Manhattan at Times Square.\n4 out of 5 stars.\n5.6 Okay 6743 reviews.\n‎Manhattan‬ • ‎650 m from centre‬\n‎Travel Sustainable‬.\nHotel room: 1 bed.\n150 USD.\nIncludes taxes and charges.\nFree cancellation.\nNo prepayment needed.",
    name: "The Manhattan at Times Square",
    rating: 5.6, // Review Score provided
    reviewCount: 6743,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/524489007.jpg?k=01c5dc6fd2f06c64eb77b591b05199107565815851e4c6f0a9e61e99e93129e1&o=",
    tag: ["All", "Travel Sustainable", "Free cancellation", "No prepayment needed", "New York"],
    location: "Manhattan, New York",
    distance: "650 m from centre",
    sustainability: "Travel Sustainable",
    propertyFeatures: "1 bed",
    roomType: "Hotel room",
    originalPrice: "150 USD",
    currentPrice: "150 USD",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: "No prepayment needed"
  },
  {
    id: 1106729,
    description: "West Side YMCA.\n3 out of 5 stars.\n6.6 Pleasant 12207 reviews.\n‎Upper West Side‬ • ‎350 m from centre‬\n‎Travel Sustainable‬.\nRoom with shared bathroom: 1 bed.\nOriginal price 121 USD. Current price 93 USD.\nIncludes taxes and charges.",
    name: "West Side YMCA",
    rating: 6.6, // Review Score provided
    reviewCount: 12207,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/204079362.jpg?k=ad3e3b9e935728478fd7d2c0c871198135bb522158b35ed9f23cb312a067110d&o=",
    tag: ["All", "Travel Sustainable", "New York"],
    location: "Upper West Side, New York",
    distance: "350 m from centre",
    sustainability: "Travel Sustainable",
    propertyFeatures: "1 bed",
    roomType: "Room with shared bathroom",
    originalPrice: "121 USD",
    currentPrice: "93 USD",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: ""
  },
  {
    id: 8665027,
    description: "The Herald by LuxUrban, Trademark Collection by Wyndham.\n7.8 Good 6001 reviews.\n‎Manhattan‬ • ‎2 km from centre‬.\nHotel room: 1 bed.\nOriginal price 164 USD. Current price 148 USD.\nIncludes taxes and charges.",
    name: "The Herald by LuxUrban, Trademark Collection by Wyndham",
    rating: 7.8, // Review Score provided
    reviewCount: 6001,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/482620202.jpg?k=ab59fa0eeee2529ff6c9e5efdef48ee28c9bce51b849a5576dacaca5f44d68e1&o=",
    tag: ["All", "Travel Sustainable", "New York"],
    location: "Manhattan, New York",
    distance: "2 km from centre",
    sustainability: "Travel Sustainable",
    propertyFeatures: "1 bed",
    roomType: "Hotel room",
    originalPrice: "164 USD",
    currentPrice: "148 USD",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: ""
  },

  {
    id: 57746,
    description: "33 Seaport Hotel New York.\n5 out of 5 stars.\n8.5 Very good 421 reviews.\n‎Wall Street - Financial District‬ • ‎7 km from centre‬\n‎Travel Sustainable‬.\n1 bed.\nOriginal price 442 USD. Current price 402 USD..\nIncludes taxes and charges.",
    name: "33 Seaport Hotel New York",
    rating: 8.5, // Review Score provided
    reviewCount: 421,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/460282320.jpg?k=f6d06474dd39260e9941d571e653b5cea9ee332abeffdf830e62a91378b6450c&o=",
    tag: ["All", "Travel Sustainable", "New York"],
    location: "Wall Street - Financial District, New York",
    distance: "7 km from centre",
    sustainability: "Travel Sustainable",
    propertyFeatures: "1 bed",
    roomType: "Hotel room",
    originalPrice: "442 USD",
    currentPrice: "402 USD",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: ""
  },
  {
    id: 906253,
    description: "citizenM New York Times Square.\n4 out of 5 stars.\n8.6 Fabulous 3685 reviews.\n‎Manhattan‬ • ‎750 m from centre‬\n‎Travel Sustainable‬.\n Hotel room : 1 bed.\n199 USD.\nIncludes taxes and charges.",
    name: "citizenM New York Times Square",
    rating: 8.6, // Review Score provided
    reviewCount: 3685,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/267120053.jpg?k=c7b756d37479abc632d41b09d15c925efa1de89f08216ff41f49eb209a89c7c8&o=",
    tag: ["All", "Travel Sustainable", "New York"],
    location: "Manhattan, New York",
    distance: "750 m from centre",
    sustainability: "Travel Sustainable",
    propertyFeatures: "1 bed",
    roomType: "Hotel room",
    originalPrice: "199 USD",
    currentPrice: "199 USD",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: ""
  },
  {
    id: 483674,
    description: "Fairfield Inn & Suites by Marriott New York Midtown Manhattan/Penn Station.\n4 out of 5 stars.\n8.2 Very good 5322 reviews.\n‎Hell's Kitchen‬ • ‎2.1 km from centre‬\n‎Travel Sustainable‬.\n Hotel room : 1 bed.\n199 USD.\nIncludes taxes and charges.\nFree cancellation.\nNo prepayment needed.",
    name: "Fairfield Inn & Suites by Marriott New York Midtown Manhattan/Penn Station",
    rating: 8.2, // Review Score provided
    reviewCount: 5322,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/484773554.jpg?k=17b3249d5fddd02e62542574e24b1fb9bd97189932962f932a2ac17d16fec03e&o=",
    tag: ["All", "Travel Sustainable", "Free cancellation", "No prepayment needed", "New York"],
    location: "Hell's Kitchen, New York",
    distance: "2.1 km from centre",
    sustainability: "Travel Sustainable",
    propertyFeatures: "1 bed",
    roomType: "Hotel room",
    originalPrice: "199 USD",
    currentPrice: "199 USD",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: "No prepayment needed"
  },
  {
    id: 6162805,
    description: "Delta Hotels by Marriott New York Times Square.\n4 out of 5 stars.\n7.7 Good 2055 reviews.\n‎Hell's Kitchen‬ • ‎1.6 km from centre‬\n‎Travel Sustainable‬.\n Hotel room : 2 beds.\n163 USD.\nIncludes taxes and charges.\nNo prepayment needed.",
    name: "Delta Hotels by Marriott New York Times Square",
    rating: 7.7, // Review Score provided
    reviewCount: 2055,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/486726691.jpg?k=bb8a6dfe3b3ec5559f25cf82cdac21f2ed880321c75eb0f441c371e02755a295&o=",
    tag: ["All", "Travel Sustainable", "New York"],
    location: "Hell's Kitchen, New York",
    distance: "1.6 km from centre",
    sustainability: "Travel Sustainable",
    propertyFeatures: "2 beds",
    roomType: "Hotel room",
    originalPrice: "163 USD",
    currentPrice: "163 USD",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: "No prepayment needed"
  },
  {
    id: 599534,
    description: "Fairfield Inn by Marriott New York Manhattan/Financial District.\n3 out of 5 stars.\n7.5 Good 3314 reviews.\n‎Wall Street - Financial District‬ • ‎7 km from centre‬\n‎Travel Sustainable‬.\n Hotel room : 1 bed.\nOriginal price 163 USD. Current price 147 USD..\nIncludes taxes and charges.\nNo prepayment needed.",
    name: "Fairfield Inn by Marriott New York Manhattan/Financial District",
    rating: 7.5, // Review Score provided
    reviewCount: 3314,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/453249379.jpg?k=89b5cd75af1110c53e2d9da452f70d5ab697cb7378044d680e2457f760a540e4&o=",
    tag: ["All", "Travel Sustainable", "New York"],
    location: "Wall Street - Financial District, New York",
    distance: "7 km from centre",
    sustainability: "Travel Sustainable",
    propertyFeatures: "1 bed",
    roomType: "Hotel room",
    originalPrice: "163 USD",
    currentPrice: "147 USD",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: "No prepayment needed"
  },
  {
    id: 617931,
    description: "Hilton Garden Inn New York/Midtown Park Avenue.\n3 out of 5 stars.\n8.0 Very good 1719 reviews.\n‎Manhattan‬ • ‎2.4 km from centre‬\n‎Travel Sustainable‬.\n Hotel room : 1 bed.\n181 USD.\nIncludes taxes and charges.\nNo prepayment needed.",
    name: "Hilton Garden Inn New York/Midtown Park Avenue",
    rating: 8.0, // Review Score provided
    reviewCount: 1719,
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/485684166.jpg?k=234227d2f4af3fe5596c46f6e370a0f1b26bf8403ed0d004380551ba71a84a87&o=",
    tag: ["All", "Travel Sustainable", "New York"],
    location: "Manhattan, New York",
    distance: "2.4 km from centre",
    sustainability: "Travel Sustainable",
    propertyFeatures: "1 bed",
    roomType: "Hotel room",
    originalPrice: "181 USD",
    currentPrice: "181 USD",
    taxesAndCharges: "Includes taxes and charges",
    prepayment: "No prepayment needed"
  },
  
  {
    id: 1,
    name: "Niranta Transit Hotel",
    image:
      "https://cf.bstatic.com/xdata/images/hotel/square60/336693267.jpg?k=58e5dfa4e3d86ae8efe46eda7f9d6c78868f2c7d7b861f21239b1f7bd7287120&o=",
    description:
      "Niranta Transit Hotel Terminal 2 Arrivals/Landside.\n4 out of 5 stars.\n7.3 Good 3887 reviews.\n‎Andheri‬ • ‎2.5 km from center‬\n‎Travel Sustainable‬\n‎This property has free cribs available‬.\n Hotel room : 1 bed.\nOriginal price 1017 AED. Current price 458 AED..\n+82 AED taxes and charges.\nNo prepayment needed.",
    reviewCount: 3887,
    rating: 7.3,
    tag: ["All", "Mumbai", "2"],
    location: "Andheri",
    distance: "2.5 km from center",
    sustainability: "Travel Sustainable",
    propertyFeatures: "Free cribs available",
    roomType: "1 bed",
    originalPrice: "1017 AED",
    currentPrice: "458 AED",
    taxesAndCharges: "+82 AED taxes and charges",
    prepayment: "No prepayment needed",
  },
  {
    id: 8778629,
    name: "Hotel Ariana Residency",
    image:
      "https://cf.bstatic.com/xdata/images/hotel/square60/392019082.jpg?k=d825a25be93ddb1a2bc16e0fdb573ec8bcb9ed69e286890b207ca558748dca32&o=",
    description:
      "Hotel Ariana Residency.\n4 out of 5 stars.\n7.0 Good 461 reviews.\n‎Western Suburbs‬ • ‎7 km from center‬\n‎1.5 km from beach‬\n‎Travel Sustainable‬\n‎This property has cribs available‬.\n Hotel room : 2 beds.\nOriginal price 359 AED. Current price 256 AED..\n+31 AED taxes and charges.",
    reviewCount: 461,
    rating: 7,
    tag: ["All", "Mumbai", "1"],
    location: "Western Suburbs",
    distance: "7 km from center",
    sustainability: "Travel Sustainable",
    propertyFeatures: "Cribs available",
    roomType: "2 beds",
    originalPrice: "359 AED",
    currentPrice: "256 AED",
    taxesAndCharges: "+31 AED taxes and charges",
    prepayment: "No prepayment needed",
  },
  {
    id: 1362336,
    name: "Hotel Linkway",
    image:
      "https://cf.bstatic.com/xdata/images/hotel/square60/162282985.jpg?k=8442c7cc0bfdd20c0d7f92e11aa6dbf52e8b3836565582fb6514f212aa2778a8&o=",
    description:
      "Hotel Linkway.\n2 out of 5 stars.\n8.4 Very Good 304 reviews.\n‎Khar‬ • ‎4.6 km from center‬\n‎1.4 km from beach‬.\n Hotel room : Beds: 1 double or 2 twins.\n142 AED.\n+17 AED taxes and charges.\nFree cancellation.\nNo prepayment needed.",
    reviewCount: 304,
    rating: 8.4,
    tag: ["All", "Mumbai", "1"],
    location: "Khar",
    distance: "4.6 km from center",
    sustainability: "",
    propertyFeatures: "",
    roomType: "Beds: 1 double or 2 twins",
    originalPrice: "142 AED",
    currentPrice: "159 AED",
    taxesAndCharges: "+17 AED taxes and charges",
    prepayment: "No prepayment needed",
  },
  {
    id: 10723872,
    name: "HOTEL NEW VERTIGO SUITES",
    image:
      "https://cf.bstatic.com/xdata/images/hotel/square60/497264132.jpg?k=5e923c56e1c734b5ca2cdb305531b8e9291847b6fc870abba3911989b6c73678&o=",
    description:
      "HOTEL NEW VERTIGO SUITES.\n2 out of 5 stars.\n7.9 Good 345 reviews.\n‎Central Suburbs‬ • ‎500 m from center‬.\n1 bed.\n100 AED.\n+12 AED taxes and charges.",
    reviewCount: 345,
    rating: 7.9,
    tag: ["All", "Mumbai", "1"],
    location: "Central Suburbs",
    distance: "500 m from center",
    sustainability: "",
    propertyFeatures: "",
    roomType: "1 bed",
    originalPrice: "100 AED",
    currentPrice: "112 AED",
    taxesAndCharges: "+12 AED taxes and charges",
    prepayment: "No prepayment needed",
  },
  {
    id: 1300736,
    name: "JW Marriott Mumbai Sahar Airport",
    image:
      "https://cf.bstatic.com/xdata/images/hotel/square60/465549681.jpg?k=8c903ab7bf0fd906a3fe7b456463805c4026db2dab6706341a83d385160f0f9b&o=",
    description:
      "JW Marriott Mumbai Sahar Airport.\n5 out of 5 stars.\n8.6 Excellent 2749 reviews.\n‎Western Suburbs‬ • ‎3 km from center‬\n‎Travel Sustainable‬\n‎This property has free cribs available‬.\n Hotel room : 2 beds.\n576 AED.\n+104 AED taxes and charges.\nNo prepayment needed.",
    reviewCount: 2749,
    rating: 8.6,
    tag: ["All", "Mumbai", "1"],
    location: "Western Suburbs",
    distance: "3 km from center",
    sustainability: "Travel Sustainable",
    propertyFeatures: "Free cribs available",
    roomType: "2 beds",
    originalPrice: "576 AED",
    currentPrice: "680 AED",
    taxesAndCharges: "+104 AED taxes and charges",
    prepayment: "No prepayment needed",
  },
  {
    id: 249951,
    name: "The Leela Mumbai",
    image:
      "https://cf.bstatic.com/xdata/images/hotel/square60/31159733.jpg?k=d951c8b28ff9a7e3df8ff1cae2d40b22c5ce5434e9218a9ce30e4cdb9353851d&o=",
    description:
      "The Leela Mumbai.\n5 out of 5 stars.\n8.6 Excellent 3453 reviews.\n‎Western Suburbs‬ • ‎3.7 km from center‬\n‎Travel Sustainable‬.\n1 bed.\n558 AED.\n+100 AED taxes and charges.\nNo prepayment needed.",
    reviewCount: 3453,
    rating: 8.6,
    tag: ["All", "Mumbai", "1"],
    location: "Western Suburbs",
    distance: "3.7 km from center",
    sustainability: "Travel Sustainable",
    propertyFeatures: "",
    roomType: "1 bed",
    originalPrice: "558 AED",
    currentPrice: "658 AED",
    taxesAndCharges: "+100 AED taxes and charges",
    prepayment: "No prepayment needed",
  },
  {
    id: 11308398,
    name: "Hotel Beverly Palace Santacruz",
    image:
      "https://cf.bstatic.com/xdata/images/hotel/square60/524195587.jpg?k=2d226361de0829779850a07ef8ad74c2cc58e3a9b7215dbeb20e85bcf20afed1&o=",
    description:
      "Hotel Beverly Palace Santacruz.\n3 out of 5 stars.\n7.6 Good 37 reviews.\n‎Santacruz‬ • ‎1.6 km from center‬.\n Hotel room : 2 beds.\nOriginal price 199 AED. Current price 179 AED..\n+22 AED taxes and charges.\nNo prepayment needed.",
    reviewCount: 37,
    rating: 7.6,
    tag: ["All", "Mumbai", "1"],
    location: "Santacruz",
    distance: "1.6 km from center",
    sustainability: "",
    propertyFeatures: "",
    roomType: "2 beds",
    originalPrice: "199 AED",
    currentPrice: "201 AED",
    taxesAndCharges: "+22 AED taxes and charges",
    prepayment: "No prepayment needed",
  },
  {
    id: 8154912,
    name: "Hotel BENTLY",
    image:
      "https://cf.bstatic.com/xdata/images/hotel/square60/531521145.jpg?k=a58b34130edcebd80c5a3821022dfe56a862a2f1856831cd8f70b577de97ebdc&o=",
    description:
      "Hotel BENTLY.\n3 out of 5 stars.\n7.4 Good 302 reviews.\n‎Western Suburbs‬ • ‎4.6 km from center‬\n‎This property has free cribs available‬.\n Hotel room : 2 beds.\nOriginal price 191 AED. Current price 171 AED..\n+24 AED taxes and charges.\nNo prepayment needed.",
    reviewCount: 302,
    rating: 7.4,
    tag: ["All", "Mumbai", "1"],
    location: "Western Suburbs",
    distance: "4.6 km from center",
    sustainability: "",
    propertyFeatures: "Free cribs available",
    roomType: "2 beds",
    originalPrice: "191 AED",
    currentPrice: "195 AED",
    taxesAndCharges: "+24 AED taxes and charges",
    prepayment: "No prepayment needed",
   },
  
   {
    id: 1548237,
    name: "Taj Santacruz",
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/125011716.jpg?k=a11b2cf7938b3214652ec26dbe0a51850850e41270bf9a43e986e3d3de848748&o=",
    description: "Taj Santacruz.\n5 out of 5 stars.\n8.8 Excellent 3469 reviews.\n3.1 km from center\n2.8 km from beach\nTravel Sustainable\n1 bed.\nOriginal price 576 AED. Current price 575 AED.\n+104 AED taxes and charges.",
    reviewCount: 3469,
    rating: 8.8,
    tag: ["All", "Mumbai", "5"],
    location: "Santacruz",
    distance: "3.1 km from center, 2.8 km from beach",
    sustainability: "Travel Sustainable",
    propertyFeatures: "1 bed",
    roomType: "Hotel room",
    originalPrice: "576 AED",
    currentPrice: "575 AED",
    taxesAndCharges: "+104 AED taxes and charges",
    prepayment: "No prepayment needed",
  },
  {
    id: 9360612,
    name: "Novotel Mumbai International Airport",
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/520102818.jpg?k=bdbc0aacaf999cc4cda474366fa4ba04504acdaa4b8f7c31560674abd0bcf029&o=",
    description: "Novotel Mumbai International Airport.\n5 out of 5 stars.\n8.5 Very Good 728 reviews.\nWestern Suburbs • 3.8 km from center\nTravel Sustainable\nHotel room : 1 bed.\nOriginal price 465 AED. Current price 465 AED.\n+84 AED taxes and charges.\nNo prepayment needed.",
    reviewCount: 728,
    rating: 8.5,
    tag: ["All", "Mumbai", "5"],
    location: "Western Suburbs",
    distance: "3.8 km from center",
    sustainability: "Travel Sustainable",
    propertyFeatures: "Hotel room : 1 bed",
    roomType: "Hotel room",
    originalPrice: "465 AED",
    currentPrice: "465 AED",
    taxesAndCharges: "+84 AED taxes and charges",
    prepayment: "No prepayment needed",
  },
  {
    id: 1781955,
    name: "Niranta Transit Hotel Mumbai Airport - At Arrivals",
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/336693532.jpg?k=86ff2c5bb735ba1061a35f977c362a4b9c6dd65ec067c4398de0c0377e0c3ebd&o=",
    description: "Niranta Transit Hotel Mumbai Airport - At Arrivals.\n4 out of 5 stars.\n7.2 Good 1257 reviews.\nAndheri • 2.6 km from center\nTravel Sustainable\nThis property has free cribs available.\nHotel room : 1 bed.\nOriginal price 1017 AED. Current price 458 AED.\n+82 AED taxes and charges.\nFree cancellation.\nNo prepayment needed.",
    reviewCount: 1257,
    rating: 7.2,
    tag: ["All", "Mumbai", "4"],
    location: "Andheri",
    distance: "2.6 km from center",
    sustainability: "Travel Sustainable",
    propertyFeatures: "Hotel room : 1 bed",
    roomType: "Hotel room",
    originalPrice: "1017 AED",
    currentPrice: "458 AED",
    taxesAndCharges: "+82 AED taxes and charges",
    prepayment: "No prepayment needed",
  },
  {
    id: 1453101,
    name: "Niranta Transit Hotel Terminal 2 Arrivals/Landside",
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/336693267.jpg?k=58e5dfa4e3d86ae8efe46eda7f9d6c78868f2c7d7b861f21239b1f7bd7287120&o=",
    description: "Niranta Transit Hotel Terminal 2 Arrivals/Landside.\n4 out of 5 stars.\n7.3 Good 3887 reviews.\nAndheri • 2.5 km from center\nTravel Sustainable\nThis property has free cribs available.\nHotel room : 1 bed.\nOriginal price 1017 AED. Current price 458 AED.\n+82 AED taxes and charges.\nNo prepayment needed.",
    reviewCount: 3887,
    rating: 7.3,
    tag: ["All", "Mumbai", "4"],
    location: "Andheri",
    distance: "2.5 km from center",
    sustainability: "Travel Sustainable",
    propertyFeatures: "Hotel room : 1 bed",
    roomType: "Hotel room",
    originalPrice: "1017 AED",
    currentPrice: "458 AED",
    taxesAndCharges: "+82 AED taxes and charges",
    prepayment: "No prepayment needed",
  },
  {
    id: 3777484,
    name: "Radisson Mumbai Andheri MIDC",
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/244881053.jpg?k=a593947570d0eaef20e446f4e6d899f7f2651a2d9ab7f2f14d6100131ce5869d&o=",
    description: "Radisson Mumbai Andheri MIDC.\n4 out of 5 stars.\n8.2 Very Good 1473 reviews.\nWestern Suburbs • 4.8 km from center\nTravel Sustainable\nHotel room : 1 bed.\nOriginal price 488 AED. Current price 439 AED.\n+101 AED taxes and charges.\nNo prepayment needed.",
    reviewCount: 1473,
    rating: 8.2,
    tag: ["All", "Mumbai", "4"],
    location: "Western Suburbs",
    distance: "4.8 km from center",
    sustainability: "Travel Sustainable",
    propertyFeatures: "Hotel room : 1 bed",
    roomType: "Hotel room",
    originalPrice: "488 AED",
    currentPrice: "439 AED",
    taxesAndCharges: "+101 AED taxes and charges",
    prepayment: "No prepayment needed",
  },
  {
    id: 401149,
    name: "Hotel Oriental Aster- Mumbai International Airport",
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/342883399.jpg?k=e2713955a2bcb82f59cb344396d359f1385a6454213a3bdd62be5f80c25ac283&o=",
    description: "Hotel Oriental Aster- Mumbai International Airport.\n4 out of 5 stars.\n7.6 Good 996 reviews.\nWestern Suburbs • 3.9 km from center\nTravel Sustainable\nHotel room : 1 bed.\n287 AED.\n+34 AED taxes and charges.",
    reviewCount: 996,
    rating: 7.6,
    tag: ["All", "Mumbai", "4"],
    location: "Western Suburbs",
    distance: "3.9 km from center",
    sustainability: "Travel Sustainable",
    propertyFeatures: "Hotel room : 1 bed",
    roomType: "Hotel room",
    originalPrice: "287 AED",
    currentPrice: "287 AED",
    taxesAndCharges: "+34 AED taxes and charges",
    prepayment: "No prepayment needed",
  },
  {
    id: 191605,
    name: "Novotel Mumbai Juhu Beach",
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/252005217.jpg?k=9d4ae263d055f30dd78158dbf2f6c34900e5c9078b1a545caa28a3c8466b6a69&o=",
    description: "Novotel Mumbai Juhu Beach.\n5 out of 5 stars.\n6.7 Pleasant 2328 reviews.\nJuhu • 7 km from center\nBeachfront\nTravel Sustainable\nThis property has free cribs available.\nHotel room : 2 beds.\n430 AED.\n+77 AED taxes and charges.\nNo prepayment needed.",
    reviewCount: 2328,
    rating: 6.7,
    tag: ["All", "Mumbai", "5"],
    location: "Juhu",
    distance: "7 km from center, Beachfront",
    sustainability: "Travel Sustainable",
    propertyFeatures: "Hotel room : 2 beds",
    roomType: "Hotel room",
    originalPrice: "430 AED",
    currentPrice: "430 AED",
    taxesAndCharges: "+77 AED taxes and charges",
    prepayment: "No prepayment needed",
  },
  {
    id: 283624,
    name: "Hilton Mumbai International Airport Hotel",
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/483825117.jpg?k=3e9ad1b06f2d88d6794eb7662223650800963fe496eafdcb0f84ee8f6b516182&o=",
    description: "Hilton Mumbai International Airport Hotel.\n5 out of 5 stars.\n7.8 Good 1682 reviews.\nWestern Suburbs • 3.2 km from center\nTravel Sustainable\nThis property has free cribs available.\nHotel room : 1 bed.\n509 AED.\n+92 AED taxes and charges.\nNo prepayment needed.",
    reviewCount: 1682,
    rating: 7.8,
    tag: ["All", "Mumbai", "5"],
    location: "Western Suburbs",
    distance: "3.2 km from center",
    sustainability: "Travel Sustainable",
    propertyFeatures: "Hotel room : 1 bed",
    roomType: "Hotel room",
    originalPrice: "509 AED",
    currentPrice: "509 AED",
    taxesAndCharges: "+92 AED taxes and charges",
    prepayment: "No prepayment needed",
  },
  {
    id: 10869399,
    name: "Home2 Renaissance Club",
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/497678662.jpg?k=e5f2c4da109176ab3b790f7a604c5b4d8780e1a8e3e8491afa715055d25c780c&o=",
    description: "Home2 Renaissance Club.\n4 out of 5 stars.\n7.1 Good 78 reviews.\nWestern Suburbs • 8 km from center\n350 m from beach.\nPrivate suite : 1 bed.\nOriginal price 187 AED. Current price 169 AED.\n+20 AED taxes and charges.\nFree cancellation.\nNo prepayment needed.",
    reviewCount: 78,
    rating: 7.1,
    tag: ["All", "Mumbai", "4"],
    location: "Western Suburbs",
    distance: "8 km from center, 350 m from beach",
    sustainability: "Travel Sustainable",
    propertyFeatures: "Private suite : 1 bed",
    roomType: "Private suite",
    originalPrice: "187 AED",
    currentPrice: "169 AED",
    taxesAndCharges: "+20 AED taxes and charges",
    prepayment: "No prepayment needed",
  },
  {
    id: 238999,
    name: "Courtyard by Marriott Mumbai International Airport",
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/461660051.jpg?k=b8149f7ac7756b80accb066e0feb56c0dd13e0534048da3cfd782d5e366cdabb&o=",
    description: "Courtyard by Marriott Mumbai International Airport.\n5 out of 5 stars.\n8.1 Very Good 1425 reviews.\nWestern Suburbs • 4.4 km from center\nTravel Sustainable\nThis property has free cribs available.\nHotel room : 3 beds.\n465 AED.\n+84 AED taxes and charges.\nNo prepayment needed.",
    reviewCount: 1425,
    rating: 8.1,
    tag: ["All", "Mumbai", "5"],
    location: "Western Suburbs",
    distance: "4.4 km from center",
    sustainability: "Travel Sustainable",
    propertyFeatures: "Hotel room : 3 beds",
    roomType: "Hotel room",
    originalPrice: "465 AED",
    currentPrice: "465 AED",
    taxesAndCharges: "+84 AED taxes and charges",
    prepayment: "No prepayment needed",
  },
  {
    id: 11439321,
    name: "Hotel Blue Wellington - Near Mumbai Airport",
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/525317739.jpg?k=9d5777279f83674b9df81da003102b08f54e5413733b8926da5e32ed4d24fcc5&o=",
    description: "Hotel Blue Wellington - Near Mumbai Airport.\n3 out of 5 stars.\n6.1 Pleasant 11 reviews.\nPowai • 3.7 km from center\nTravel Sustainable.\nHotel room : 1 bed.\nOriginal price 115 AED. Current price 86 AED.\n+10 AED taxes and charges.\nNo prepayment needed.",
    reviewCount: 11,
    rating: 6.1,
    tag: ["All", "Mumbai", "3"],
    location: "Powai",
    distance: "3.7 km from center",
    sustainability: "Travel Sustainable",
    propertyFeatures: "Hotel room : 1 bed",
    roomType: "Hotel room",
    originalPrice: "115 AED",
    currentPrice: "86 AED",
    taxesAndCharges: "+10 AED taxes and charges",
    prepayment: "No prepayment needed",
  },
  {
    id: 74722,
    name: "Taj Lands End",
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/13800549.jpg?k=2239f273986987fa71ef3c94ab6f127feb2b859ab63f057980c074689c62c04c&o=",
    description: "Taj Lands End.\n5 out of 5 stars.\n8.6 Excellent 3600 reviews.\nBandra • 7 km from center\n1.9 km from beach\nTravel Sustainable\nThis property has free cribs available.\n1 bed.\n670 AED.\n+121 AED taxes and charges.",
    reviewCount: 3600,
    rating: 8.6,
    tag: ["All", "Mumbai", "5"],
    location: "Bandra",
    distance: "7 km from center, 1.9 km from beach",
    sustainability: "Travel Sustainable",
    propertyFeatures: "1 bed",
    roomType: "Hotel room",
    originalPrice: "670 AED",
    currentPrice: "670 AED",
    taxesAndCharges: "+121 AED taxes and charges",
    prepayment: "No prepayment needed",
  },
  {
    id: 274997,
    name: "Grand Residency Hotel & Serviced Apartments",
    image: "https://cf.bstatic.com/xdata/images/hotel/square60/81595285.jpg?k=96c0c716695a9b26ef9383955532f8cdc4408ad2c318485524ef9100a9610e2b&o=",
    description: "Grand Residency Hotel & Serviced Apartments.\n4 out of 5 stars.\n7.5 Good 354 reviews.\nBandra • 5 km from center\n1.8 km from beach\nTravel Sustainable\nThis property has free cribs available.\nPrivate room : 2 beds.\nOriginal price 487 AED. Current price 365 AED.\n+66 AED taxes and charges.",
    reviewCount: 354,
    rating: 7.5,
    tag: ["All", "Mumbai", "4"],
    location: "Bandra",
    distance: "5 km from center, 1.8 km from beach",
    sustainability: "Travel Sustainable",
    propertyFeatures: "Private room : 2 beds",
    roomType: "Private room",
    originalPrice: "487 AED",
    currentPrice: "365 AED",
    taxesAndCharges: "+66 AED taxes and charges",
    prepayment: "No prepayment needed",
   },
  
  //Some dummies
  // {
  //   id: 242661,
  //   name: "The Lalit Mumbai",
  //   image:
  //     "https://cf.bstatic.com/xdata/images/hotel/square60/39904407.jpg?k=b5c4e5f87e79e5cb2cb6dc686f15e37ad41556d78b66b9cb0bda45ab11b732b2&o=",
  //   description:
  //     "The Lalit Mumbai.\n5 out of 5 stars.\n8.5 Excellent 3152 reviews.\n‎Western Suburbs‬ • ‎4.3 km from center‬\n‎Travel Sustainable‬\n‎This property has free cribs available‬.\n Hotel room : 1 bed.\nOriginal price 542 AED. Current price 271 AED..\n+49 AED taxes and charges.",
  //   reviewCount: 3152,
  //   rating: 8.5,
  //   tag: ["All", "Mumbai", "1"],
  //   location: "Western Suburbs",
  //   distance: "4.3 km from center",
  //   sustainability: "Travel Sustainable",
  //   propertyFeatures: "Free cribs available",
  //   roomType: "1 bed",
  //   originalPrice: "542 AED",
  //   currentPrice: "320 AED",
  //   taxesAndCharges: "+49 AED taxes and charges",
  //   prepayment: "No prepayment needed",
  // },
  // {
  //   id: 1075419,
  //   name: "Hyatt Regency Mumbai International Airport",
  //   image:
  //     "https://cf.bstatic.com/xdata/images/hotel/square60/1909376.jpg?k=3f37351a330044dc0089a433b43fbb6178fbef407e9e14d1a368ba7cb2042b8a&o=",
  //   description:
  //     "Hyatt Regency Mumbai International Airport.\n5 out of 5 stars.\n8.2 Very Good 3359 reviews.\n‎Western Suburbs‬ • ‎3.9 km from center‬\n‎Travel Sustainable‬\n‎This property has free cribs available‬.\n Hotel room : 1 bed.\n556 AED.\n+101 AED taxes and charges.",
  //   reviewCount: 3359,
  //   rating: 8.2,
  //   tag: ["All", "Mumbai", "1"],
  //   location: "Western Suburbs",
  //   distance: "3.9 km from center",
  //   sustainability: "Travel Sustainable",
  //   propertyFeatures: "Free cribs available",
  //   roomType: "1 bed",
  //   originalPrice: "556 AED",
  //   currentPrice: "657 AED",
  //   taxesAndCharges: "+101 AED taxes and charges",
  //   prepayment: "No prepayment needed",
  // },
  // {
  //   id: 10710561,
  //   name: "Hotel Rang Sharda",
  //   image:
  //     "https://cf.bstatic.com/xdata/images/hotel/square60/179169309.jpg?k=dab58356f91b6da40fcdd51f64a6d997d1c89f839bcb02e924f4b5f42f8b79e9&o=",
  //   description:
  //     "Hotel Rang Sharda.\n3 out of 5 stars.\n7.1 Good 198 reviews.\n‎Bandra‬ • ‎1.5 km from center‬.\n Hotel room : 2 beds.\nOriginal price 143 AED. Current price 131 AED..\n+17 AED taxes and charges.",
  //   reviewCount: 198,
  //   rating: 7.1,
  //   tag: ["All", "Mumbai", "1"],
  //   location: "Bandra",
  //   distance: "1.5 km from center",
  //   sustainability: "",
  //   propertyFeatures: "",
  //   roomType: "2 beds",
  //   originalPrice: "143 AED",
  //   currentPrice: "148 AED",
  //   taxesAndCharges: "+17 AED taxes and charges",
  //   prepayment: "No prepayment needed",
  // },
  // {
  //   id: 1298223,
  //   name: "The Westin Mumbai Garden City",
  //   image:
  //     "https://cf.bstatic.com/xdata/images/hotel/square60/46100589.jpg?k=ef5f23c57a10ed76717f9f50a2a4c6c3b48c26b7a993a3e3aeb8704a1698da4d&o=",
  //   description:
  //     "The Westin Mumbai Garden City.\n5 out of 5 stars.\n8.3 Very Good 873 reviews.\n‎Western Suburbs‬ • ‎7.7 km from center‬\n‎Travel Sustainable‬\n‎This property has free cribs available‬.\n Hotel room : 1 bed.\n317 AED.\n+57 AED taxes and charges.",
  //   reviewCount: 873,
  //   rating: 8.3,
  //   tag: ["All", "Mumbai", "1"],
  //   location: "Western Suburbs",
  //   distance: "7.7 km from center",
  //   sustainability: "Travel Sustainable",
  //   propertyFeatures: "Free cribs available",
  //   roomType: "1 bed",
  //   originalPrice: "317 AED",
  //   currentPrice: "374 AED",
  //   taxesAndCharges: "+57 AED taxes and charges",
  //   prepayment: "No prepayment needed",
  // },
  // {
  //   id: 1119156,
  //   name: "Sahara Star Hotel",
  //   image:
  //     "https://cf.bstatic.com/xdata/images/hotel/square60/230147165.jpg?k=8e99fbb431032d49538224f4a5ba569a306b9028db4762d54b41d8d2daea8160&o=",
  //   description:
  //     "Sahara Star Hotel.\n5 out of 5 stars.\n8.0 Very Good 1784 reviews.\n‎Western Suburbs‬ • ‎500 m from center‬\n‎Travel Sustainable‬\n‎This property has free cribs available‬.\n Hotel room : 1 bed.\n615 AED.\n+111 AED taxes and charges.",
  //   reviewCount: 1784,
  //   rating: 8,
  //   tag: ["All", "Mumbai", "1"],
  //   location: "Western Suburbs",
  //   distance: "500 m from center",
  //   sustainability: "Travel Sustainable",
  //   propertyFeatures: "Free cribs available",
  //   roomType: "1 bed",
  //   originalPrice: "615 AED",
  //   currentPrice: "726 AED",
  //   taxesAndCharges: "+111 AED taxes and charges",
  //   prepayment: "No prepayment needed",
  // },
  // {
  //   id: 1340209,
  //   name: "The Orchid - An Ecotel Hotel",
  //   image:
  //     "https://cf.bstatic.com/xdata/images/hotel/square60/47095926.jpg?k=35d1089d2e60bc76de51281d19c4c2d2b72e2065a33a44c78ec254c7fa0c31b0&o=",
  //   description:
  //     "The Orchid - An Ecotel Hotel.\n5 out of 5 stars.\n8.0 Very Good 3148 reviews.\n‎Western Suburbs‬ • ‎5.4 km from center‬\n‎Travel Sustainable‬\n‎This property has free cribs available‬.\n Hotel room : 2 beds.\n346 AED.\n+62 AED taxes and charges.",
  //   reviewCount: 3148,
  //   rating: 8,
  //   tag: ["All", "Mumbai", "1"],
  //   location: "Western Suburbs",
  //   distance: "5.4 km from center",
  //   sustainability: "Travel Sustainable",
  //   propertyFeatures: "Free cribs available",
  //   roomType: "2 beds",
  //   originalPrice: "346 AED",
  //   currentPrice: "408 AED",
  //   taxesAndCharges: "+62 AED taxes and charges",
  //   prepayment: "No prepayment needed",
  // },
  // {
  //   id: 8276928,
  //   name: "OYO 4002 Flagship Hotel Adore Inn",
  //   image:
  //     "https://cf.bstatic.com/xdata/images/hotel/square60/186259617.jpg?k=eeb588d7b6a77ab4935e0a5f38fcbe6e89a4f92ff32f9fb70b44b8ff5d1c6d4b&o=",
  //   description:
  //     "OYO 4002 Flagship Hotel Adore Inn.\n3 out of 5 stars.\n7.7 Good 192 reviews.\n‎Western Suburbs‬ • ‎6.7 km from center‬.\n1 bed.\n126 AED.\n+18 AED taxes and charges.",
  //   reviewCount: 192,
  //   rating: 7.7,
  //   tag: ["All", "Mumbai", "1"],
  //   location: "Western Suburbs",
  //   distance: "6.7 km from center",
  //   sustainability: "",
  //   propertyFeatures: "",
  //   roomType: "1 bed",
  //   originalPrice: "126 AED",
  //   currentPrice: "144 AED",
  //   taxesAndCharges: "+18 AED taxes and charges",
  //   prepayment: "No prepayment needed",
  // },
  // {
  //   id: 11316613,
  //   name: "Hotel Golders Green",
  //   image:
  //     "https://cf.bstatic.com/xdata/images/hotel/square60/211328596.jpg?k=176c5b510d19ff6a8fcbbfbd6ec015042572798c4355e5df7cf3b60056d97f10&o=",
  //   description:
  //     "Hotel Golders Green.\n4 out of 5 stars.\n7.0 Good 99 reviews.\n‎Western Suburbs‬ • ‎3.6 km from center‬\n‎1 bed.\n169 AED.\n+24 AED taxes and charges.\nFree cancellation.\nNo prepayment needed.",
  //   reviewCount: 99,
  //   rating: 7,
  //   tag: ["All", "Mumbai", "1"],
  //   location: "Western Suburbs",
  //   distance: "3.6 km from center",
  //   sustainability: "",
  //   propertyFeatures: "",
  //   roomType: "1 bed",
  //   originalPrice: "169 AED",
  //   currentPrice: "193 AED",
  //   taxesAndCharges: "+24 AED taxes and charges",
  //   prepayment: "No prepayment needed",
  // },
  // {
  //   id: 1341864,
  //   name: "Hotel Galaxy Comforts",
  //   image:
  //     "https://cf.bstatic.com/xdata/images/hotel/square60/208799983.jpg?k=b1b7157b14e13c4e739ef1d489b57e18cfd74d7a0654c82e44da5d61f6cd74c5&o=",
  //   description:
  //     "Hotel Galaxy Comforts.\n4 out of 5 stars.\n7.6 Good 185 reviews.\n‎Western Suburbs‬ • ‎3.8 km from center‬\n‎1 bed.\n201 AED.\n+28 AED taxes and charges.",
  //   reviewCount: 185,
  //   rating: 7.6,
  //   tag: ["All", "Mumbai", "1"],
  //   location: "Western Suburbs",
  //   distance: "3.8 km from center",
  //   sustainability: "",
  //   propertyFeatures: "",
  //   roomType: "1 bed",
  //   originalPrice: "201 AED",
  //   currentPrice: "229 AED",
  //   taxesAndCharges: "+28 AED taxes and charges",
  //   prepayment: "No prepayment needed",
  // },
  // {
  //   id: 10225921,
  //   name: "Hotel Parle International",
  //   image:
  //     "https://cf.bstatic.com/xdata/images/hotel/square60/1934494.jpg?k=d3a9fb6bf432aa9bb2a83fd1312ffbe8e924308a2a54f6d9e6a5eaf5494db9c1&o=",
  //   description:
  //     "Hotel Parle International.\n3 out of 5 stars.\n6.8 Good 264 reviews.\n‎Western Suburbs‬ • ‎1.4 km from center‬\n‎1 bed.\n210 AED.\n+31 AED taxes and charges.",
  //   reviewCount: 264,
  //   rating: 6.8,
  //   tag: ["All", "Mumbai", "1"],
  //   location: "Western Suburbs",
  //   distance: "1.4 km from center",
  //   sustainability: "",
  //   propertyFeatures: "",
  //   roomType: "1 bed",
  //   originalPrice: "210 AED",
  //   currentPrice: "241 AED",
  //   taxesAndCharges: "+31 AED taxes and charges",
  //   prepayment: "No prepayment needed",
  // },
  // {
  //   id: 1673391,
  //   name: "Grand Hyatt Mumbai",
  //   image:
  //     "https://cf.bstatic.com/xdata/images/hotel/square60/28494623.jpg?k=fab3ff99e2f3f59a617ee16fc129f88910ec9cf1d98a7cb97f776b4ab1ee4e02&o=",
  //   description:
  //     "Grand Hyatt Mumbai.\n5 out of 5 stars.\n8.2 Very Good 1083 reviews.\n‎Western Suburbs‬ • ‎6.2 km from center‬\n‎Travel Sustainable‬\n‎This property has free cribs available‬.\n Hotel room : 1 bed.\n529 AED.\n+96 AED taxes and charges.\nNo prepayment needed.",
  //   reviewCount: 1083,
  //   rating: 8.2,
  //   tag: ["All", "Mumbai", "1"],
  //   location: "Western Suburbs",
  //   distance: "6.2 km from center",
  //   sustainability: "Travel Sustainable",
  //   propertyFeatures: "Free cribs available",
  //   roomType: "1 bed",
  //   originalPrice: "529 AED",
  //   currentPrice: "625 AED",
  //   taxesAndCharges: "+96 AED taxes and charges",
  //   prepayment: "No prepayment needed",
  // },
  // {
  //   id: 8080864,
  //   name: "Sai Palace Grand Malad",
  //   image:
  //     "https://cf.bstatic.com/xdata/images/hotel/square60/137776109.jpg?k=ba14f0c3e8d303f77a1c61a8ac3f78a38e1930b228d9cb5dd1d5fb55a77e6e09&o=",
  //   description:
  //     "Sai Palace Grand Malad.\n4 out of 5 stars.\n7.2 Good 1642 reviews.\n‎Western Suburbs‬ • ‎3.4 km from center‬\n‎This property has free cribs available‬.\n Hotel room : 2 beds.\n145 AED.\n+21 AED taxes and charges.\nFree cancellation.\nNo prepayment needed.",
  //   reviewCount: 1642,
  //   rating: 7.2,
  //   tag: ["All", "Mumbai", "1"],
  //   location: "Western Suburbs",
  //   distance: "3.4 km from center",
  //   sustainability: "",
  //   propertyFeatures: "Free cribs available",
  //   roomType: "2 beds",
  //   originalPrice: "145 AED",
  //   currentPrice: "166 AED",
  //   taxesAndCharges: "+21 AED taxes and charges",
  //   prepayment: "No prepayment needed",
  // },
  // {
  //   id: 8991855,
  //   name: "Hotel Alfa Grand",
  //   image:
  //     "https://cf.bstatic.com/xdata/images/hotel/square60/301841570.jpg?k=3f01f6f3b11d2e6d575e05c1c44e87acfd70a6603612c48e2fd3f1247a2b848f&o=",
  //   description:
  //     "Hotel Alfa Grand.\n3 out of 5 stars.\n6.7 Good 213 reviews.\n‎Western Suburbs‬ • ‎2.3 km from center‬.\n Hotel room : 2 beds.\n189 AED.\n+27 AED taxes and charges.",
  //   reviewCount: 213,
  //   rating: 6.7,
  //   tag: ["All", "Mumbai", "1"],
  //   location: "Western Suburbs",
  //   distance: "2.3 km from center",
  //   sustainability: "",
  //   propertyFeatures: "",
  //   roomType: "2 beds",
  //   originalPrice: "189 AED",
  //   currentPrice: "216 AED",
  //   taxesAndCharges: "+27 AED taxes and charges",
  //   prepayment: "No prepayment needed",
  // },
  // {
  //   id: 1364496,
  //   name: "The Empresa Hotel",
  //   image:
  //     "https://cf.bstatic.com/xdata/images/hotel/square60/43568852.jpg?k=59b3b249e869315d16ae16073b1bb16ed6c68456c3fe13fb4475c0e3f3bc843c&o=",
  //   description:
  //     "The Empresa Hotel.\n4 out of 5 stars.\n8.1 Very Good 591 reviews.\n‎Western Suburbs‬ • ‎3 km from center‬\n‎Travel Sustainable‬\n‎This property has free cribs available‬.\n Hotel room : 1 bed.\n420 AED.\n+76 AED taxes and charges.",
  //   reviewCount: 591,
  //   rating: 8.1,
  //   tag: ["All", "Mumbai", "1"],
  //   location: "Western Suburbs",
  //   distance: "3 km from center",
  //   sustainability: "Travel Sustainable",
  //   propertyFeatures: "Free cribs available",
  //   roomType: "1 bed",
  //   originalPrice: "420 AED",
  //   currentPrice: "496 AED",
  //   taxesAndCharges: "+76 AED taxes and charges",
  //   prepayment: "No prepayment needed",
  // },
  // {
  //   id: 8448207,
  //   name: "Hotel Metro Palace",
  //   image:
  //     "https://cf.bstatic.com/xdata/images/hotel/square60/66626599.jpg?k=5f85e2d7e1814b86d3f018d9d0889bdf1cbad9f876025c12d3016a82e76bdc5a&o=",
  //   description:
  //     "Hotel Metro Palace.\n3 out of 5 stars.\n6.8 Good 585 reviews.\n‎Western Suburbs‬ • ‎1.3 km from center‬.\n Hotel room : 2 beds.\n208 AED.\n+30 AED taxes and charges.",
  //   reviewCount: 585,
  //   rating: 6.8,
  //   tag: ["All", "Mumbai", "1"],
  //   location: "Western Suburbs",
  //   distance: "1.3 km from center",
  //   sustainability: "",
  //   propertyFeatures: "",
  //   roomType: "2 beds",
  //   originalPrice: "208 AED",
  //   currentPrice: "238 AED",
  //   taxesAndCharges: "+30 AED taxes and charges",
  //   prepayment: "No prepayment needed",
  // },
  // {
  //   id: 1197274,
  //   name: "VITS Mumbai International Airport T2",
  //   image:
  //     "https://cf.bstatic.com/xdata/images/hotel/square60/220984196.jpg?k=eb4c20df004f3b46f89fd352f68325a97e2c5ad819828d642b9e59cddc57e0b9&o=",
  //   description:
  //     "VITS Mumbai International Airport T2.\n4 out of 5 stars.\n7.1 Good 4266 reviews.\n‎Andheri‬ • ‎500 m from center‬\n‎This property has free cribs available‬.\n Hotel room : 1 bed.\n400 AED.\n+72 AED taxes and charges.",
  //   reviewCount: 4266,
  //   rating: 7.1,
  //   tag: ["All", "Mumbai", "1"],
  //   location: "Andheri",
  //   distance: "500 m from center",
  //   sustainability: "",
  //   propertyFeatures: "Free cribs available",
  //   roomType: "1 bed",
  //   originalPrice: "400 AED",
  //   currentPrice: "472 AED",
  //   taxesAndCharges: "+72 AED taxes and charges",
  //   prepayment: "No prepayment needed",
  // },
  // {
  //   id: 1643387,
  //   name: "HOTEL GRAND WESTEND",
  //   image:
  //     "https://cf.bstatic.com/xdata/images/hotel/square60/39050431.jpg?k=33e726b0f6a9bc6bfaa40ac35d2db8ff400d9622bc510ff65da7b6e3e90e8e00&o=",
  //   description:
  //     "HOTEL GRAND WESTEND.\n4 out of 5 stars.\n7.5 Good 413 reviews.\n‎Western Suburbs‬ • ‎1.2 km from center‬\n‎1 bed.\n299 AED.\n+43 AED taxes and charges.",
  //   reviewCount: 413,
  //   rating: 7.5,
  //   tag: ["All", "Mumbai", "1"],
  //   location: "Western Suburbs",
  //   distance: "1.2 km from center",
  //   sustainability: "",
  //   propertyFeatures: "",
  //   roomType: "1 bed",
  //   originalPrice: "299 AED",
  //   currentPrice: "342 AED",
  //   taxesAndCharges: "+43 AED taxes and charges",
  //   prepayment: "No prepayment needed",
  // },
  // {
  //   id: 1637711,
  //   name: "Keys Select Hotel Nestor",
  //   image:
  //     "https://cf.bstatic.com/xdata/images/hotel/square60/30651109.jpg?k=75ec6e51df3cc5ee4c8d43e74f48e8d1b9474f0c91cb61613d06b7642255ac4e&o=",
  //   description:
  //     "Keys Select Hotel Nestor.\n4 out of 5 stars.\n7.8 Good 253 reviews.\n‎Andheri‬ • ‎6 km from center‬\n‎1 bed.\n262 AED.\n+38 AED taxes and charges.",
  //   reviewCount: 253,
  //   rating: 7.8,
  //   tag: ["All", "Mumbai", "1"],
  //   location: "Andheri",
  //   distance: "6 km from center",
  //   sustainability: "",
  //   propertyFeatures: "",
  //   roomType: "1 bed",
  //   originalPrice: "262 AED",
  //   currentPrice: "300 AED",
  //   taxesAndCharges: "+38 AED taxes and charges",
  //   prepayment: "No prepayment needed",
  // },
  // {
  //   id: 1237529,
  //   name: "Keys Select Hotel Aqua Green",
  //   image:
  //     "https://cf.bstatic.com/xdata/images/hotel/square60/26785364.jpg?k=067d8a1fc2f3877d3ee894d8e38d601e6a3cc9b8d7d1b7db3e367bd04118ff80&o=",
  //   description:
  //     "Keys Select Hotel Aqua Green.\n4 out of 5 stars.\n7.9 Good 257 reviews.\n‎Andheri‬ • ‎5.2 km from center‬\n‎1 bed.\n216 AED.\n+31 AED taxes and charges.",
  //   reviewCount: 257,
  //   rating: 7.9,
  //   tag: ["All", "Mumbai", "1"],
  //   location: "Andheri",
  //   distance: "5.2 km from center",
  //   sustainability: "",
  //   propertyFeatures: "",
  //   roomType: "1 bed",
  //   originalPrice: "216 AED",
  //   currentPrice: "247 AED",
  //   taxesAndCharges: "+31 AED taxes and charges",
  //   prepayment: "No prepayment needed",
  // },
  // {
  //   id: 1139054,
  //   name: "Hotel Samrat Mumbai",
  //   image:
  //     "https://cf.bstatic.com/xdata/images/hotel/square60/183057216.jpg?k=290b8c4648fbab03df55c9ee8bc5de6f13db45ba241e23b6a2082764175560c3&o=",
  //   description:
  //     "Hotel Samrat Mumbai.\n3 out of 5 stars.\n6.7 Good 90 reviews.\n‎Andheri‬ • ‎2.4 km from center‬.\n Hotel room : 2 beds.\n176 AED.\n+25 AED taxes and charges.",
  //   reviewCount: 90,
  //   rating: 6.7,
  //   tag: ["All", "Mumbai", "1"],
  //   location: "Andheri",
  //   distance: "2.4 km from center",
  //   sustainability: "",
  //   propertyFeatures: "",
  //   roomType: "2 beds",
  //   originalPrice: "176 AED",
  //   currentPrice: "201 AED",
  //   taxesAndCharges: "+25 AED taxes and charges",
  //   prepayment: "No prepayment needed",
  // },
  // {
  //   id: 1119307,
  //   name: "Hotel Sea Sands",
  //   image:
  //     "https://cf.bstatic.com/xdata/images/hotel/square60/17093623.jpg?k=77ad5c381af5c365ff36a515f812db2d5e4dc2ee07c11d1d58fbaccd0ff2f39e&o=",
  //   description:
  //     "Hotel Sea Sands.\n3 out of 5 stars.\n6.9 Good 264 reviews.\n‎Juhu‬ • ‎600 m from center‬.\n Hotel room : 1 bed.\n219 AED.\n+31 AED taxes and charges.",
  //   reviewCount: 264,
  //   rating: 6.9,
  //   tag: ["All", "Mumbai", "1"],
  //   location: "Juhu",
  //   distance: "600 m from center",
  //   sustainability: "",
  //   propertyFeatures: "",
  //   roomType: "1 bed",
  //   originalPrice: "219 AED",
  //   currentPrice: "250 AED",
  //   taxesAndCharges: "+31 AED taxes and charges",
  //   prepayment: "No prepayment needed",
  //  },
  
  
  
  
  
  
  ];